package crowdfund.controller;

import crowdfund.dao.UserDAO;
import crowdfund.model.User;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class RegisterController {

    @FXML private TextField nameField, emailField, roleField; // Text fields for user input: name, email, and role.
    @FXML private PasswordField passwordField; // Password field for user's password.

    /**
     * Handles the registration process.
     * Creates a new User object with data from the input fields,
     * registers the user using UserDAO, and then opens the login screen.
     */
    public void register() {
        UserDAO dao = new UserDAO(); // Creates a UserDAO object to interact with the user data.
        User u = new User(0, nameField.getText(), emailField.getText(),
                passwordField.getText(), roleField.getText()); // Creates a new User object with data from the input fields.  The ID is set to 0, likely auto-generated by the database.
        dao.register(u); // Registers the new user in the database.
        openLogin(); // Opens the login screen after successful registration.
    }

    /**
     * Opens the login screen.
     * Loads the login.fxml file and sets it as the scene for the current stage.
     */
    public void openLogin() {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/crowdfund/fxml/login.fxml")); // Creates an FXMLLoader to load the login.fxml file.
            Stage s = (Stage) nameField.getScene().getWindow(); // Gets the current stage from one of the input fields.
            s.setScene(new Scene(loader.load())); // Sets the scene of the stage to the login screen.
        } catch (Exception e) { e.printStackTrace(); } // Handles any exceptions that occur during the loading process.  Prints the stack trace for debugging.
    }
}
